### ISSUE TITLE
Add to Packal.org

### ISSUE THREAD

**Issue by frdmn** [elkatwork/alfred-dict.cc-workflow#5]
Would be nice if you could add the workflow there

**Comment by pfankhauser** [comment]
+1

**Comment by Erfahrungen** [comment]
Hi guys, I'm not sure if the developer of this workflow is still active so I felt free to add it myself.

http://www.packal.org/workflow/dictcc-translate-english-german

I hope that's alright. 
Marco

**Comment by frdmn** [comment]
Nice! :+1:

**Comment by elkatwork** [comment]
I did not pay much attention on this project in the past, sorry.
Thanks for uploading it!
