### ISSUE TITLE
Fix `usage` part in README.md

### ISSUE THREAD

**Issue by iDuuck** [elkatwork/alfred-dict.cc-workflow#6]
Just installed the workflow and found out, that the keyword is `dict` and not `translate`. `translate` is reserved for Google Translate I think.

**Comment by Erfahrungen** [comment]
https://github.com/elkatwork/alfred-dict.cc-workflow/pull/7

**Comment by elkatwork** [comment]
Fixed in https://github.com/elkatwork/alfred-dict.cc-workflow/pull/7
