### ISSUE TITLE
Adding a delay between keystrokes

### ISSUE THREAD

**Issue by Erfahrungen** [elkatwork/alfred-dict.cc-workflow#8]
I'm currently with a slow internet connection and the instant results after every keystroke causing problems. Adding a delay between keystrokes would fix this.

**Comment by elkatwork** [comment]
I set the workflow to "automatic delay after last character typed". Please try if that helps with your problem. If it doesn't, there is also an option to set it to a fixed delay (e.g. 200ms).
https://github.com/elkatwork/alfred-dict.cc-workflow/commit/7cb2c37d9a7f64d53011e601bb1283593f6766fb

**Comment by Erfahrungen** [comment]
Thank you so much for the update, it works great now. I'll update the workflow now on http://www.packal.org/workflow/dictcc-translate-english-german
